name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cbp2make
      run: sudo apt-get install cbp2make
    - name: create makefile
      run: cbp2make -in Alexs-Salt-Tool.cbp -out Makefile
    - name: make
      run: make
